feat: add EcsRamRole support
hashicorp/packer-plugin-alicloud pull request #57
Opened 2022-04-28 15:39 UTC by jiangytcn

Describe the change you are making here!

Authenticate with Alibaba Cloud RAM with trusted ECS RAM Role if necessary. 

Please include tests. We recommend looking at existing tests as an example. 

If your PR resolves any open issue(s), please indicate them like this so they will be closed when your PR is merged:

Closes #55

2022-04-28 15:39 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/packer-plugin-alicloud?pullRequest=57)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/packer-plugin-alicloud?pullRequest=57)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/packer-plugin-alicloud?pullRequest=57).</sub>

2022-07-27 06:35 UTC, alexyueer commented
LGTM

2022-07-28 10:08 UTC, nywilken requested changes
Hi there apologies for the delayed review. I left a couple of questions on the new fields to better understand how they should be used. 

There also appears to be a few missing changes to the documentation files and hclspec files. These changes can be generated by running `go generate ./...` within the project directory.

Please let me know if you have any questions or need help generating the missing files.

2022-07-28 10:08 UTC, nywilken commented on builder/ecs/access_config.go
> +	// Alicloud authentication mode must be provided
Is there some additional documentation needed here? It is not clear to me why mode must be provided and what are the allowed values. 

It appears that mode is a concept used internally within the code for auth related things but I'm not familiar with it. As a first time user of Alicloud I find this confusing. Have you considered adding an example template configuration to illustrate the usage, as well?

2022-08-11 19:36 UTC, merged